recordcount=1000000
operationcount=1000000
workload=site.ycsb.workloads.CoreWorkload
requestdistribution=zipfian
readproportion=0.0
updateproportion=0.0
deleteproportion=0.0
scanproportion=0.0
insertproportion=1.0
fieldcount=1
fieldlength=1024
readallfields=true
writeallfields=true
