recordcount=1000000
operationcount=5000000
workload=site.ycsb.workloads.CoreWorkload
requestdistribution=zipfian
readproportion=0.95
updateproportion=0.04
deleteproportion=0.01
scanproportion=0.0
insertproportion=0.0
fieldcount=1
fieldlength=1024
readallfields=true
writeallfields=true
maxexecutiontime=0
