# YCSB load phase workload
recordcount=1000000
operationcount=1000000
workload=site.ycsb.workloads.CoreWorkload
requestdistribution=uniform
readproportion=0
updateproportion=0
insertproportion=1.0
scanproportion=0
deleteproportion=0
fieldcount=1
fieldlength=1024
